### ISSUE TITLE
Project Week I - Review Ticket

### ISSUE THREAD

**Issue by PaarasPurohit** [PaarasPurohit/apcompsciportfolio#6]
Paaras' Review Ticket: 
https://www.youtube.com/watch?v=YMRPjy3ey3c&t=6s
https://paaraspurohit.github.io/apcompsciportfolio/project-week-one

**Comment by syeung2** [comment]
I'm not really sure how you are going to implement your code in your project. I heard a lot of definition of what your role is but how/what is your role going to be on this project. Your video was also way over the time limit and your definition of your roles could definitely have been cut. I am not seeing a lot of progress being made here so there will definitely need a lot of work to be done. I did enjoy the visual in Paaras' part in the video that was well done.
Score 4.2
